Algoritmo "crescente"

Var

    X, Y : inteiro

Inicio

      escreval("Digite dois numeros:")
      leia(X)
      leia(Y)

      enquanto X <> Y faca

         se X > Y entao
            escreval("DECRESCENTE!")
         senao
            escreval("CRESCENTE!")
         fimse
         
         escreval("Digite outros dois numeros:")
         leia(X)
         leia(Y)
           
      fimenquanto

Fimalgoritmo